# Generated by Django 3.2.7 on 2021-10-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_formulario_reuniones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
