# Generated by Django 3.2.7 on 2021-10-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinscripcion',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=20),
        ),
    ]
