# Generated by Django 3.2.7 on 2021-10-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadmin',
            name='direccion',
        ),
    ]
